"""Project paths and default settings."""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
OUTPUT_DIR = PROJECT_ROOT / "output"

RTMPOSE_ONNX_URL = (
    "https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/"
    "rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.zip"
)
RTMPOSE_INPUT_SIZE = (192, 256)
RTMPOSE_BACKEND = "onnxruntime"
RTMPOSE_DEVICE = "cpu"

YOLO_MODEL_NAME = "yolo26m.pt"
YOLO_MODEL_PATH = MODELS_DIR / YOLO_MODEL_NAME
DEFAULT_PERSON_CONFIDENCE = 0.3

DETECT_DEDUP_IOU = 0.70
DETECT_DEDUP_CONTAIN = 0.80

BYTETRACK_CONFIG = Path(__file__).resolve().parent / "sport_bytetrack.yaml"

STABILIZER_MAX_LOST_FRAMES = 120
STABILIZER_MIN_APPEARANCE = 0.5
STABILIZER_MAX_DIST_RATIO = 0.22
STABILIZER_APPEARANCE_WEIGHT = 0.6
STABILIZER_POSITION_WEIGHT = 0.4
STABILIZER_MAX_COST = 0.6
STABILIZER_APPEARANCE_ALPHA = 0.5

SELECT_PREDICT_MAX_DT = 5

SELECT_COLOR_MIN_SIM = 0.30
SELECT_COLOR_POS_TIEBREAK = 0.15
SELECT_TRACKLET_GRACE = 10
SELECT_CONTEST_MARGIN = 0.15
SELECT_CONTEST_FRAMES = 4
SELECT_REASSIGN_DIST_RATIO = 0.15
SELECT_VOTE_WINDOW = 15

COLOR_ID_KEYPOINTS = (5, 6, 11, 12)
COLOR_ID_HIST_BINS = (8, 8)
COLOR_ID_MIN_SCORE = 0.3
COLOR_ID_EMA_ALPHA = 0.0

MIN_LANDMARK_VISIBILITY = 0.3

OVERLAY_SCALE = 1.2

JOINT_MIN_SCORE = 0.4
RISK_KNEE_VALGUS_MAX = 12.0
RISK_TRUNK_LEAN_MAX = 30.0

LAND_MIN_JUMP_RATIO = 0.30
LAND_MIN_AIR_RATIO = 0.20
LAND_MAX_AIR_FRAMES = 12
LAND_MIN_SIDE_FRAMES = 3
LAND_ABSORB_FRAMES = 6
LAND_SMOOTH = 3
LESS_KNEE_FLEX_IC_MIN = 30.0
LESS_HIP_FLEX_IC_MIN = 30.0
LESS_TRUNK_FLEX_IC_MIN = 10.0
LESS_TRUNK_LEAN_MAX = 30.0
LESS_KNEE_VALGUS_IC_MAX = 12.0
LESS_STANCE_NARROW = 0.8
LESS_STANCE_WIDE = 2.2
LESS_SYMM_MAX = 0.15
LESS_KNEE_FLEX_DISP_MIN = 45.0
LESS_KNEE_VALGUS_DISP_MAX = 8.0

LESS_SUBSET_MOD_SCORE = 2
LESS_SUBSET_HIGH_SCORE = 4

RISK_VALGUS_FRAME_MOD = 0.10
RISK_VALGUS_FRAME_HIGH = 0.25
RISK_TRUNK_FRAME_MOD = 0.15
RISK_STIFF_LANDING_RATE = 0.50
RISK_VALGUS_LANDING_RATE = 0.50
RISK_COMPOSITE_MOD = 30
RISK_COMPOSITE_HIGH = 60

FALL_BASELINE_PCTL = 80.0
FALL_HEIGHT_DROP_RATIO = 0.55
FALL_VERTICALITY_MAX = 0.50
FALL_AXIS_ANGLE_MIN = 50.0
FALL_TRUNK_ANGLE_MIN = 55.0
FALL_ASPECT_MAX = 1.10
FALL_MIN_ELONGATION = 1.30
FALL_MIN_KEYPOINTS = 6
FALL_MIN_FRAMES = 5
FALL_GAP_FRAMES = 3
FALL_DROP_WINDOW = 12
FALL_DROP_RATIO = 0.45

FUSED_W_COLOR = 0.45
FUSED_W_TRAJ  = 0.55

FUSED_REASSOC_MAX_COST = 0.55

FUSED_CONTINUITY_POS_GATE = 0.10
FUSED_REASSOC_POS_GATE    = 0.12
FUSED_RELINK_POS_GATE     = 0.30

FUSED_SWAP_MARGIN = 0.04

FUSED_CONFIRM_FRAMES = 3
FUSED_TENTATIVE_MAX_LOST = 4
FUSED_NEW_TRACK_MIN_CONF = 0.5

FUSED_COLOR_HARD_GATE = 0.70

FUSED_COLOR_WATCHDOG_MIN = 0.45
FUSED_COLOR_WATCHDOG_FRAMES = 2


FUSED_LOST_RELAX_AFTER = 3

FUSED_COLOR_UNKNOWN_COST = 0.5

FUSED_COLOR_EMA_ALPHA = 0.05

FUSED_KALMAN_PROCESS_NOISE = 8.0
FUSED_KALMAN_MEAS_NOISE = 10.0

FUSED_MAX_LOST_FRAMES = 120

FUSED_TRAJ_LEN = 60

TRAJ_ARROW_FRAMES = 8.0
TRAJ_MIN_SPEED = 1.5
TRAJ_ARROW_3D_GAIN = 2.5

POSE_TRAIL_SAMPLES = 14

RISK_CLUSTER_GAP = 5

BOX3D_DEPTH_RATIO = 0.18
BOX3D_SHOULDER_RATIO = 0.26
BOX3D_DEPTH_DX = 1.0
BOX3D_DEPTH_DY = 1.0

RFDETR_PERSON_CLASS_ID = 1
MEDIAPIPE_MODEL_COMPLEXITY = 1
MEDIAPIPE_MIN_DET_CONF = 0.5

VIDEO_EXTENSIONS = (".mp4", ".mov", ".avi", ".mkv")
